name: Update main README

on:
  push:
    branches:
      - main
    paths:
      - "article-*/**"
      - "article-*"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update README
        run: python .github/scripts/update_readme.py
        
      - name: Commit changes if README was modified
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update main README.md with new published articles"
            git push
          fi
